name: sliver_header_delegate
description: A flexible sliver header delegate that allows easily customize your SliverHeader
version: 0.0.5
homepage: https://github.com/miroslava-podybailo/flutter_sliver_header_delegate
repository: https://github.com/miroslava-podybailo/flutter_sliver_header_delegate
issue_tracker: https://github.com/miroslava-podybailo/flutter_sliver_header_delegate/issues
documentation: https://github.com/miroslava-podybailo/flutter_sliver_header_delegate/blob/master/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  extra_pedantic: ^1.2.0
